# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77705f424da7e5f81854acbb8226802546256cf7223bfeb1f17524583f51824684724b517f4c148ad8ceae08e4585872eaddc15eee2de28e3558c94257af4417

test:
  secret_key_base: 822e6e41d21672009716b99de527468931fbef85180f44701df4655225e0b3aabd77b12c5d4d68be245693db9fcbae657b761dd0f9b55c0fed48c16478205667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
